name: geomosaic
channels:
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - archspec=0.2.5
  - boltons=25.0.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cffi=1.17.1
  - colorama=0.4.6
  - conda=24.11.3
  - conda-libmamba-solver=24.9.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - distro=1.9.0
  - fmt=11.1.4
  - frozendict=2.4.7
  - h2=4.3.0
  - hmmer=3.4
  - hpack=4.1.0
  - hyperframe=6.1.0
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libarchive=3.8.2
  - libcurl=8.17.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libiconv=1.18
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmamba=1.5.12
  - libmambapy=1.5.12
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libsolv=0.7.35
  - libsqlite=3.44.2
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - lzo=2.10
  - mamba=1.5.12
  - menuinst=2.4.1
  - ncurses=6.4.20240210
  - openssl=3.6.0
  - pip=23.3.1
  - pluggy=1.6.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.13
  - python_abi=3.10
  - readline=8.2
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - ruamel.yaml=0.18.16
  - ruamel.yaml.clib=0.2.14
  - setuptools=68.2.2
  - tk=8.6.13
  - truststore=0.10.3
  - wheel=0.42.0
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml-cpp=0.8.0
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - appdirs==1.4.4
      - attrs==23.1.0
      - biopython==1.83
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - configargparse==1.7
      - connection-pool==0.0.3
      - contourpy==1.2.0
      - cycler==0.12.1
      - datrie==0.8.2
      - docutils==0.20.1
      - dpath==2.1.6
      - et-xmlfile==1.1.0
      - fastjsonschema==2.19.0
      - fonttools==4.46.0
      - geomosaic==1.2.2
      - gitdb==4.0.11
      - gitpython==3.1.40
      - humanfriendly==10.0
      - idna==3.6
      - jinja2==3.1.2
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.2
      - jupyter-core==5.5.0
      - kiwisolver==1.4.5
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - nbformat==5.9.2
      - networkx==3.2.1
      - numpy==1.26.2
      - openpyxl==3.1.2
      - packaging==23.2
      - pandas==2.2.0
      - pillow==10.1.0
      - plac==1.4.1
      - platformdirs==4.0.0
      - psutil==5.9.6
      - pulp==2.7.0
      - pyparsing==3.1.1
      - python-dateutil==2.9.0.post0
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - referencing==0.31.1
      - requests==2.31.0
      - reretry==0.11.8
      - rpds-py==0.13.2
      - six==1.16.0
      - smart-open==6.4.0
      - smmap==5.0.1
      - snakemake==7.32.4
      - stopit==1.1.2
      - tabulate==0.9.0
      - throttler==1.2.2
      - toposort==1.10
      - tqdm==4.66.1
      - traitlets==5.14.0
      - tzdata==2025.2
      - urllib3==2.1.0
      - wrapt==1.16.0
      - yte==1.5.1
