name: geomosaic
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - _sysroot_linux-64_curr_repodata_hack=3=h5bd9786_13
  - aioeasywebdav=2.4.0=pyha770c72_0
  - aiohttp=3.8.3=py310h5764c6d_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alsa-lib=1.2.8=h166bdaf_0
  - amply=0.1.5=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attmap=0.13.2=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bbmap=39.01=h5c4e2a8_0
  - bcrypt=3.2.2=py310h5764c6d_1
  - bedtools=2.30.0=h468198e_3
  - binutils_impl_linux-64=2.40=hf600244_0
  - blast=2.13.0=hf3cf87c_0
  - boost-cpp=1.74.0=h75c5d50_8
  - boto3=1.26.66=pyhd8ed1ab_0
  - botocore=1.29.67=pyhd8ed1ab_0
  - bowtie2=2.5.1=py310h8d7afc0_0
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - brotlipy=0.7.0=py310h5764c6d_1005
  - bwa=0.7.17=h7132678_9
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.12.7=ha878542_0
  - cachetools=5.3.0=pyhd8ed1ab_0
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310h255011f_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - circos=0.69.8=hdfd78af_1
  - coin-or-cbc=2.10.8=h3786ebc_0
  - coin-or-cgl=0.60.6=h6f57e76_2
  - coin-or-clp=1.17.7=hc56784d_2
  - coin-or-osi=0.108.7=h2720bb7_2
  - coin-or-utils=2.11.6=h202d8b1_2
  - coincbc=2.10.8=0_metapackage
  - colorama=0.4.6=pyhd8ed1ab_0
  - configargparse=1.5.3=pyhd8ed1ab_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - contourpy=1.0.7=py310hdf3cbec_0
  - cryptography=39.0.1=py310h34c0648_0
  - curl=7.87.0=hdc1c0ab_0
  - cutadapt=4.2=py310h1425a21_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - datrie=0.8.2=py310h5764c6d_6
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - diamond=2.1.3=hb97b32f_0
  - dnaio=0.10.0=py310h1425a21_0
  - docutils=0.19=py310hff52083_1
  - dpath=2.1.4=py310hff52083_0
  - dropbox=11.36.0=pyhd8ed1ab_0
  - entrez-direct=16.2=he881be0_1
  - exceptiongroup=1.1.0=pyhd8ed1ab_0
  - expat=2.5.0=h27087fc_0
  - fastqc=0.11.9=hdfd78af_1
  - filechunkio=1.8=py_2
  - filelock=3.9.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.38.0=py310h5764c6d_1
  - fraggenescan=1.31=hec16e2b_4
  - freetype=2.12.1=hca18f0e_1
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.3.3=py310h5764c6d_0
  - ftputil=5.0.4=pyhd8ed1ab_0
  - gcc_impl_linux-64=12.2.0=hcc96c02_19
  - gettext=0.21.1=h27087fc_0
  - gfortran_impl_linux-64=12.2.0=h55be85b_19
  - giflib=5.2.1=h36c2ea0_2
  - git=2.39.1=pl5321h693f4a3_0
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.30=pyhd8ed1ab_0
  - glimmerhmm=3.0.4=pl5321h87f3376_5
  - google-api-core=1.34.0=pyhd8ed1ab_0
  - google-api-python-client=2.77.0=pyhd8ed1ab_0
  - google-auth=2.16.0=pyh1a96a4e_1
  - google-auth-httplib2=0.1.0=pyhd8ed1ab_1
  - google-cloud-core=1.3.0=py_0
  - google-cloud-storage=1.19.1=py_0
  - google-crc32c=1.1.2=py310he8fe98e_4
  - google-resumable-media=2.4.1=pyhd8ed1ab_0
  - googleapis-common-protos=1.57.1=pyhd8ed1ab_0
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=12.2.0=hcc96c02_19
  - harfbuzz=6.0.0=h8e241bc_0
  - hmmer=3.3.2=h87f3376_2
  - httplib2=0.21.0=pyhd8ed1ab_0
  - humanfriendly=10.0=py310hff52083_4
  - icu=70.1=h27087fc_0
  - idba=1.1.3=1
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_resources=5.10.2=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - isa-l=2.30.0=ha770c72_4
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jmespath=1.0.1=pyhd8ed1ab_0
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_core=5.2.0=py310hff52083_0
  - k8=0.2.5=hd03093a_2
  - kaiju=1.9.2=h5b5514e_0
  - kernel-headers_linux-64=3.10.0=h4a8ded7_13
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py310hbf28c38_1
  - krb5=1.20.1=h81ceb04_0
  - lcms2=2.14=hfd0df8a_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcblas=3.9.0=16_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=h36d4200_3
  - libcurl=7.87.0=hdc1c0ab_0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-devel_linux-64=12.2.0=h3b97bd3_19
  - libgcc-ng=12.2.0=h65d4601_19
  - libgd=2.3.3=h5aea950_4
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.74.1=h606061b_1
  - libgomp=12.2.0=h65d4601_19
  - libhwloc=2.9.0=hd6dc26d_0
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.4=h166bdaf_0
  - liblapack=3.9.0=16_linux64_openblas
  - liblapacke=3.9.0=16_linux64_openblas
  - libnghttp2=1.51.0=hff17c54_0
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libpng=1.6.39=h753d276_0
  - libprotobuf=3.20.2=h6239696_0
  - libsanitizer=12.2.0=h46fd767_19
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.40.0=h753d276_0
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx-devel_linux-64=12.2.0=h3b97bd3_19
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.5.0=h6adf6a1_2
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libwebp=1.2.4=h1daa5a0_1
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.10.3=h7463322_0
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=8.0.1=hc9558a2_0
  - logmuse=0.2.6=pyh8c360ce_0
  - make=4.3=hd18ef5c_1
  - markdown-it-py=2.1.0=pyhd8ed1ab_0
  - markupsafe=2.1.2=py310h1fa729e_0
  - matplotlib-base=3.7.0=py310he60537e_0
  - maxbin2=2.2.7=he1b5a44_1
  - mdurl=0.1.0=pyhd8ed1ab_0
  - megahit=1.2.9=h5b5514e_2
  - minimap2=2.24=h7132678_1
  - multidict=6.0.4=py310h1fa729e_0
  - munkres=1.0.7=py_1
  - nbformat=5.7.3=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - numpy=1.24.2=py310h8deb116_0
  - oauth2client=4.1.3=py_0
  - openjdk=17.0.3=h58dac75_5
  - openjpeg=2.5.0=hfec8fc6_2
  - openmp=8.0.1=0
  - openssl=3.0.8=h0b41bf4_0
  - packaging=23.0=pyhd8ed1ab_0
  - pandas=1.5.3=py310h9b08913_0
  - pango=1.50.14=hd33c08f_0
  - paramiko=3.0.0=pyhd8ed1ab_0
  - pbzip2=1.1.13=0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.40=hc3806b6_0
  - peppy=0.35.4=pyhd8ed1ab_0
  - perl=5.32.1=2_h7f98852_perl5
  - perl-archive-tar=2.40=pl5321hdfd78af_0
  - perl-b-cow=0.007=pl5321h166bdaf_0
  - perl-base=2.23=pl5321hdfd78af_2
  - perl-business-isbn=3.007=pl5321hdfd78af_0
  - perl-business-isbn-data=20210112.006=pl5321hdfd78af_0
  - perl-carp=1.38=pl5321hdfd78af_4
  - perl-clone=0.46=pl5321hec16e2b_0
  - perl-common-sense=3.75=pl5321hdfd78af_0
  - perl-compress-raw-bzip2=2.201=pl5321h87f3376_1
  - perl-compress-raw-zlib=2.105=pl5321h87f3376_0
  - perl-config-general=2.65=pl5321hdfd78af_0
  - perl-constant=1.33=pl5321hdfd78af_2
  - perl-data-dumper=2.183=pl5321hec16e2b_1
  - perl-digest-hmac=1.04=pl5321hdfd78af_0
  - perl-digest-md5=2.58=pl5321hec16e2b_1
  - perl-digest-perl-md5=1.9=pl5321hdfd78af_2
  - perl-encode=3.19=pl5321hec16e2b_1
  - perl-encode-locale=1.05=pl5321hdfd78af_7
  - perl-exporter=5.72=pl5321hdfd78af_2
  - perl-exporter-tiny=1.002002=pl5321hdfd78af_0
  - perl-extutils-makemaker=7.66=pl5321hd8ed1ab_0
  - perl-file-listing=6.15=pl5321hdfd78af_0
  - perl-file-spec=3.48_01=pl5321hdfd78af_2
  - perl-font-ttf=1.06=pl5321hdfd78af_1
  - perl-gd=2.76=pl5321h5b5514e_1
  - perl-html-parser=3.80=pl5321h9f5acd7_0
  - perl-html-tagset=3.20=pl5321hdfd78af_4
  - perl-http-cookies=6.10=pl5321hdfd78af_0
  - perl-http-daemon=6.15=pl5321hdfd78af_0
  - perl-http-date=6.05=pl5321hdfd78af_0
  - perl-http-message=6.36=pl5321hdfd78af_0
  - perl-http-negotiate=6.01=pl5321hdfd78af_4
  - perl-io-compress=2.201=pl5321h87f3376_0
  - perl-io-html=1.004=pl5321hdfd78af_0
  - perl-io-socket-ssl=2.074=pl5321hdfd78af_0
  - perl-io-string=1.08=pl5321hdfd78af_4
  - perl-io-zlib=1.14=pl5321hdfd78af_0
  - perl-json=4.10=pl5321hdfd78af_0
  - perl-json-xs=2.34=pl5321h9f5acd7_5
  - perl-libwww-perl=6.39=pl5321hdfd78af_1
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321hec16e2b_1
  - perl-lwp-mediatypes=6.04=pl5321hdfd78af_1
  - perl-lwp-simple=6.39=pl5321h9ee0642_5
  - perl-math-bezier=0.01=pl5321hdfd78af_2
  - perl-math-round=0.07=pl5321hdfd78af_2
  - perl-math-vecstat=0.08=pl5321hdfd78af_2
  - perl-mime-base64=3.16=pl5321hec16e2b_2
  - perl-module-implementation=0.09=pl5321hdfd78af_3
  - perl-module-runtime=0.016=pl5321hdfd78af_2
  - perl-net-http=6.22=pl5321hdfd78af_0
  - perl-net-ssleay=1.92=pl5321hf14f497_1
  - perl-ntlm=1.09=pl5321hdfd78af_5
  - perl-number-format=1.75=pl5321hdfd78af_4
  - perl-params-validate=1.31=pl5321hec16e2b_0
  - perl-parent=0.236=pl5321hdfd78af_2
  - perl-pathtools=3.75=pl5321hec16e2b_3
  - perl-readonly=2.05=pl5321hdfd78af_1
  - perl-regexp-common=2017060201=pl5321hdfd78af_1
  - perl-scalar-list-utils=1.62=pl5321hec16e2b_1
  - perl-set-intspan=1.19=pl5321hdfd78af_2
  - perl-socket=2.027=pl5321hec16e2b_3
  - perl-statistics-basic=1.6611=pl5321hdfd78af_3
  - perl-svg=2.87=pl5321hdfd78af_0
  - perl-test-fatal=0.016=pl5321hdfd78af_0
  - perl-text-format=0.62=pl5321hdfd78af_0
  - perl-time-hires=1.9764=pl5321hec16e2b_2
  - perl-time-local=1.30=pl5321hdfd78af_0
  - perl-timedate=2.33=pl5321hdfd78af_2
  - perl-try-tiny=0.31=pl5321hdfd78af_1
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - perl-uri=5.12=pl5321hdfd78af_0
  - perl-url-encode=0.03=pl5321h9ee0642_0
  - perl-www-robotrules=6.02=pl5321hdfd78af_4
  - perl-xml-parser=2.44_01=pl5321hc3e0081_1003
  - pigz=2.6=h27826a3_0
  - pillow=9.4.0=py310h023d228_1
  - pip=23.0=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - plac=1.3.5=pyhd8ed1ab_0
  - platformdirs=3.0.0=pyhd8ed1ab_0
  - pluggy=1.0.0=pyhd8ed1ab_5
  - ply=3.11=py_1
  - prettytable=3.6.0=pyhd8ed1ab_0
  - protobuf=3.20.2=py310hd8f1fbe_1
  - psutil=5.9.4=py310h5764c6d_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulp=2.7.0=py310hff52083_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pynacl=1.5.0=py310h5764c6d_2
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.19.3=py310h1fa729e_0
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.2.1=pyhd8ed1ab_0
  - python=3.10.9=he550d4f_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-irodsclient=1.1.6=pyhd8ed1ab_0
  - python-isal=1.1.0=py310h5764c6d_1
  - python_abi=3.10=3_cp310
  - pytz=2022.7.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py310h5764c6d_5
  - quast=5.2.0=py310pl5321hc8f18ef_2
  - r-base=4.2.2=ha7d60f8_3
  - r-bitops=1.0_7=r42h06615bd_1
  - r-catools=1.18.2=r42h7525677_1
  - r-gplots=3.1.3=r42hc72bb7e_1
  - r-gtools=3.9.4=r42h06615bd_0
  - r-kernsmooth=2.23_20=r42hd009a43_1
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.2=pyhd8ed1ab_0
  - reretry=0.11.8=pyhd8ed1ab_0
  - rich=13.3.1=pyhd8ed1ab_1
  - rsa=4.9=pyhd8ed1ab_0
  - s3transfer=0.6.0=pyhd8ed1ab_0
  - samtools=1.6=h3f2fef4_8
  - sed=4.8=he412f7d_0
  - setuptools=67.1.0=pyhd8ed1ab_0
  - setuptools-scm=7.1.0=pyhd8ed1ab_0
  - simplejson=3.18.3=py310h1fa729e_0
  - six=1.16.0=pyh6c4a22f_0
  - slacker=0.14.0=py_0
  - smart_open=6.3.0=pyhd8ed1ab_1
  - smmap=3.0.5=pyh44b312d_0
  - snakemake-minimal=7.21.0=pyhdfd78af_0
  - spades=3.15.5=h95f258a_1
  - stone=3.3.1=pyhd8ed1ab_0
  - stopit=1.1.2=py_0
  - sysroot_linux-64=2.17=h4a8ded7_13
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tar=1.34=hb2e2bae_1
  - tbb=2021.8.0=hf52228f_0
  - throttler=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tktable=2.10=hb7b940f_3
  - tomli=2.0.1=pyhd8ed1ab_0
  - toposort=1.9=pyhd8ed1ab_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - trim-galore=0.6.10=hdfd78af_0
  - trimmomatic=0.39=hdfd78af_2
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - ubiquerg=0.6.2=pyhd8ed1ab_0
  - unicodedata2=15.0.0=py310h5764c6d_0
  - uritemplate=4.1.1=pyhd8ed1ab_0
  - urllib3=1.26.14=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wget=1.20.3=ha35d2d1_1
  - wheel=0.38.4=pyhd8ed1ab_0
  - wrapt=1.14.1=py310h5764c6d_1
  - xopen=1.7.0=py310hff52083_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-libxtst=1.2.3=h7f98852_1002
  - xorg-recordproto=1.14.2=h7f98852_1002
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.8.2=py310h5764c6d_0
  - yte=1.5.1=py310hff52083_1
  - zipp=3.12.1=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zstandard=0.19.0=py310hdeb6495_1
  - zstd=1.5.2=h3eb15da_6
  - pip:
      - mifaser==1.60
      - networkx==3.0
      - pydot==1.4.2
      - python-graphviz==0.20.1
